name: Generate Snake

on:
  schedule:
    - cron: "0 20 * * *" # Chạy hàng ngày vào 20:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: yourusername
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
